name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  just_audio_aurora:
    path: ../
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.46
  file_selector: ^1.0.3
  file_selector_aurora:
    git:
      url: https://gitlab.com/omprussia/flutter/flutter-community-plugins/file_selector_aurora

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/Bones.mp3
