name: example1
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  dio: ^4.0.6
  json_annotation: ^4.8.1
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  just_audio_aurora:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
